### ISSUE TITLE
KtLint fails to run on JDK 15

### ISSUE THREAD

**Issue by Tapchicoma** [pinterest/ktlint#1063]
## Expected Behavior

KtLint fails to run on JDK 15

## Observed Behavior

TBA

## Steps to Reproduce
- Use JDK version 15
- run KtLint check via CLI

Kotlin added JDK support in `1.4.20` version. Update is blocked, because CLI fails to run with this Kotlin version.

**Comment by BraisGabin** [comment]
> Kotlin added JDK support in `1.4.20` version. Update is blocked, because CLI fails to run with this Kotlin version.

Do you have more information about this? We are having exactly the same problem in detekt. Detekt and ktlint raise different exceptions but the problem seems the same: The executable retuned by `shadowJaraExecutable` fails when you run in on Java8. But it works with Java9 and onwards.

ktlin stack trace:
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.pinterest.ktlint.core.KtLint
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.pinterest.ktlint.KtlintCommandLine.parallel(Main.kt:567)
	at com.pinterest.ktlint.KtlintCommandLine.parallel$default(Main.kt:541)
	at com.pinterest.ktlint.KtlintCommandLine.lintFiles(Main.kt:290)
	at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:256)
	at com.pinterest.ktlint.Main.main(Main.kt:69)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.pinterest.ktlint.core.KtLint
	at com.pinterest.ktlint.internal.FileUtilsKt.lintFile(FileUtils.kt:71)
	at com.pinterest.ktlint.KtlintCommandLine.process(Main.kt:387)
	at com.pinterest.ktlint.KtlintCommandLine.access$process(Main.kt:124)
	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$2$1.call(Main.kt:281)
	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$2$1.call(Main.kt:124)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

detekt:
```

**Comment by Tapchicoma** [comment]
@BraisGabin check PR for CLI crash workaround. Not the best solution, but it works :man_shrugging:
