### ISSUE TITLE
NPE exception for 0.41.0 version

### ISSUE THREAD

**Issue by lechen26** [pinterest/ktlint#1122]
Hi

when trying to bump repository from 0.40.0 to 0.41.0 we see the following error:
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NullPointerException: entry
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.pinterest.ktlint.KtlintCommandLine.parallel(Main.kt:575)
        at com.pinterest.ktlint.KtlintCommandLine.parallel$default(Main.kt:547)
        at com.pinterest.ktlint.KtlintCommandLine.lintFiles(Main.kt:298)
        at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:262)
        at com.pinterest.ktlint.Main.main(Main.kt:70)
Caused by: java.lang.NullPointerException: entry
        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
        at java.base/java.util.zip.ZipFile.getInputStream(ZipFile.java:372)
        at com.pinterest.ktlint.core.internal.KotlinPsiFileFactory.validateCompilerExtensionsFilesPath(KotlinPsiFileFactory.kt:92)
        at com.pinterest.ktlint.core.internal.KotlinPsiFileFactory.initializePsiFileFactory(KotlinPsiFileFactory.kt:64)
        at com.pinterest.ktlint.core.internal.KotlinPsiFileFactory.acquirePsiFileFactory$ktlint_core(KotlinPsiFileFactory.kt:39)
        at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:378)
        at com.pinterest.ktlint.internal.FileUtilsKt.formatFile(FileUtils.kt:182)
        at com.pinterest.ktlint.KtlintCommandLine.process(Main.kt:366)
        at com.pinterest.ktlint.KtlintCommandLine.access$process(Main.kt:89)
        at com.pinterest.ktlint.KtlintCommandLine$lintFiles$3$1.call(Main.kt:289)
        at com.pinterest.ktlint.KtlintCommandLine$lintFiles$3$1.call(Main.kt:288)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

FAILURE: Build failed with an exception.
```

nothing has changed on the repo.
i've noticed this release includes 'breaking changes' but none of them seems to be related.

the configuration on the build.gradle looks like the following:
```

task ktlint(type: JavaExec, group: "verification") {
    description = "Check Kotlin code style."
    classpath = configurations.ktlint
    main = "com.pinterest.ktlint.Main"
    args "src/**/*.kt"
}


task ktlintFormat(type: JavaExec, group: "formatting") {
    description = "Fix Kotlin code style deviations."
    classpath = configurations.ktlint
    main = "com.pinterest.ktlint.Main"
    args "-F", "src/**/*.kt"
}

ktlint.dependsOn ktlintFormat
check.dependsOn ktlint
```

also, tried to update the path to **.kt as described on the release notes but we get the same outcome.
i see the code that trows this exception, i believe its related to this :
` zipFile.getEntry("META-INF/extensions/core.xml")`

but i have no idea why .

thanks
CL

**Comment by lechen26** [comment]
update kotlint to 1.4.31 solve this.

saw it on the release notes ` Update Kotlin to 1.4.31 version. Fixes #1063.`

10x
