### ISSUE TITLE
Upgrade to ktlint 0.41.0 (via kotlinter 3.4.0) with Java 1.8 fails due to java.lang.IllegalStateException: Could not load module definition

### ISSUE THREAD

**Issue by phildudas** [pinterest/ktlint#1128]
## Expected Behavior

before the version update, formatKotlin gradle task would run fine with the rest of my configuration (and fix problems)

## Observed Behavior

./gradlew formatKotlin results in this failure:  

> Task :app:formatKotlinMain FAILED
format worker execution error
java.lang.IllegalStateException: Could not load module definition from: VirtualFile: /Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home!/modules/java.base/module-info.class. The file might be broken by incorrect post-processing via bytecode tools. Please remove this file from the classpath.
        at org.jetbrains.kotlin.resolve.jvm.modules.JavaModuleInfo$Companion.read(JavaModuleInfo.kt:85)
        at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder.findSystemModule(CliJavaModuleFinder.kt:44)
        at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder.access$findSystemModule(CliJavaModuleFinder.kt:25)
        at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder$systemModules$1.invoke(CliJavaModuleFinder.kt:37)
        at org.jetbrains.kotlin.cli.jvm.modules.CliJavaModuleFinder$systemModules$1.invoke(CliJavaModuleFinder.kt:37)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:278)
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:265)
        at kotlin.sequences.SequencesKt___SequencesKt.none(_Sequences.kt:1329)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.addModularRoots(ClasspathRootsResolver.kt:226)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.computeRoots(ClasspathRootsResolver.kt:123)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:79)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:216)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:426)
        at com.pinterest.ktlint.core.internal.KotlinPsiFileFactory.initializePsiFileFactory(KotlinPsiFileFactory.kt:74)
        at com.pinterest.ktlint.core.internal.KotlinPsiFileFactory.acquirePsiFileFactory$ktlint_core(KotlinPsiFileFactory.kt:39)
        at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:378)
        at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:361)
        at org.jmailen.gradle.kotlinter.tasks.format.FormatWorkerAction.format(FormatWorkerAction.kt:77)
        at org.jmailen.gradle.kotlinter.tasks.format.FormatWorkerAction.formatKt(FormatWorkerAction.kt:71)
        at org.jmailen.gradle.kotlinter.tasks.format.FormatWorkerAction.access$formatKt(FormatWorkerAction.kt:18)
        at org.jmailen.gradle.kotlinter.tasks.format.FormatWorkerAction$execute$1$1.invoke(FormatWorkerAction.kt:37)
        at org.jmailen.gradle.kotlinter.tasks.format.FormatWorkerAction$execute$1$1.invoke(FormatWorkerAction.kt:18)
        at org.jmailen.gradle.kotlinter.tasks.format.FormatWorkerAction.execute(FormatWorkerAction.kt:44)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)
        at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.IllegalArgumentException
        at org.jetbrains.org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:70)
        at org.jetbrains.org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:57)
        at org.jetbrains.kotlin.resolve.jvm.modules.JavaModuleInfo$Companion$read$1.<init>(JavaModuleInfo.kt:68)
        at org.jetbrains.kotlin.resolve.jvm.modules.JavaModuleInfo$Companion.read(JavaModuleInfo.kt:68)
        ... 55 more

## Steps to Reproduce

I will try to set up a separate repo for this, but with a kotlin project targeted to Java 1.8, I had been using kotlinter 3.3.0 successfully.  Updating to 3.4.0 (which only seems to be updating ktlint to 0.41.0) resulted in this failure.  If I force kotlinter back down to 0.40.0 it works again.  

## Your Environment

* Version of ktlint used:   0.41.0
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task):  kotlinter 3.4.0, running formatKotlin task
* Version of Gradle used (if applicable):  4.1.3
* Operating System and version:  Max OSX Catalina 10.15.7
* Link to your project (if it's a public repository):

**Comment by phildudas** [comment]
jumped the gun on this one, closing

**Comment by twyatt** [comment]
Also hitting this error. @phildudas what did you do to resolve it?

**Comment by phildudas** [comment]
> Also hitting this error. @phildudas what did you do to resolve it?

I didn't end up resolving this and just froze kotlinter at 0.40.0 waiting for an update that fixed the issue.  I forget now why I closed the issue (I think I wasn't sure it was correct), but I'm going to reopen now.

**Comment by twyatt** [comment]
I was hitting this failure while using JDK11 with all versions of ktlint.

For me at least, bumping [sqldelight](https://github.com/cashapp/sqldelight) plugin from `1.4.4` to `1.5.0` fixed the issue. I was then able to use any version of ktlint (tried up to `0.41.0` and it worked).

**Comment by romtsn** [comment]
Resolved with 0.43.1 (or will be)
