### ISSUE TITLE
ktlint doesn't work with Kotlin 1.6.0

### ISSUE THREAD

**Issue by juergenzimmermann** [pinterest/ktlint#1239]
## Expected Behavior
It would be nice if ktlint would internally use Kotlin 1.6 so that the same Kotlin version would be used for a project and ktlint itself.

## Observed Behavior
When I set the classpath for Kotlin `1.6.0-M1` and have OpenJDK 17, then I get the following stacktrace:

```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NullPointerException: entry
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.pinterest.ktlint.KtlintCommandLine.parallel(Main.kt:575)
        at com.pinterest.ktlint.KtlintCommandLine.parallel$default(Main.kt:547)
        at com.pinterest.ktlint.KtlintCommandLine.lintFiles(Main.kt:298)
        at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:262)
        at com.pinterest.ktlint.Main.main(Main.kt:70)
Caused by: java.lang.NullPointerException: entry
        at java.base/java.util.Objects.requireNonNull(Objects.java:233)
        at java.base/java.util.zip.ZipFile.getInputStream(ZipFile.java:354)
        at com.pinterest.ktlint.core.internal.KotlinPsiFileFactory.validateCompilerExtensionsFilesPath(KotlinPsiFileFactory.kt:92)
        at com.pinterest.ktlint.core.internal.KotlinPsiFileFactory.initializePsiFileFactory(KotlinPsiFileFactory.kt:64)
        at com.pinterest.ktlint.core.internal.KotlinPsiFileFactory.acquirePsiFileFactory$ktlint_core(KotlinPsiFileFactory.kt:39)
        at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:149)
        at com.pinterest.ktlint.internal.FileUtilsKt.lintFile(FileUtils.kt:169)
        at com.pinterest.ktlint.KtlintCommandLine.process(Main.kt:395)
        at com.pinterest.ktlint.KtlintCommandLine.access$process(Main.kt:89)
        at com.pinterest.ktlint.KtlintCommandLine$lintFiles$3.invoke$lambda-0(Main.kt:289)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

## Steps to Reproduce
See above

## Your Environment
* Version of ktlint used: 0.42.1
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): Custom Gradle task which invokes `com.pinterest.ktlint.Main` via Gradle's JavaExec
* Version of Gradle used (if applicable): 7.2
* Operating System and version: Windows Enterprise 10 21H1
* Link to your project (if it's a public repository): -

**Comment by vRallev** [comment]
I tested with Kotlin `1.6.0-RC` and JDK 11 and the same behavior and stacktrace there.

**Comment by juergenzimmermann** [comment]
Using ktlint 0.43.0 with Kotlin 1.6.0-RC2 works fine.
