### ISSUE TITLE
Changing log factory from com.pinterest.ktlint.core.internal.LoggerFactory to com.pinterest.ktlint.core.internal.LoggerFactory

### ISSUE THREAD

**Issue by henrik242** [pinterest/ktlint#1497]
Any ideas what this is?  I see that it's [just a log statement](https://github.com/JetBrains/intellij-community/blob/13de00f66def4fd53683a9497f0c0ad50b95932f/platform/util/src/com/intellij/openapi/diagnostic/Logger.java#L76), but why is this happening?  It might have been a change to kotlin 1.7 that did it for us.
```
> Task :myapp-common:formatKotlinMain
Changing log factory from com.pinterest.ktlint.core.internal.LoggerFactory to com.pinterest.ktlint.core.internal.LoggerFactory
java.lang.Throwable
        at org.jetbrains.kotlin.com.intellij.openapi.diagnostic.Logger.logFactoryChanged(Logger.java:76)
        at org.jetbrains.kotlin.com.intellij.openapi.diagnostic.Logger.setFactory(Logger.java:49)
        at com.pinterest.ktlint.core.internal.KotlinPsiFileFactoryKt.initPsiFileFactory(KotlinPsiFileFactory.kt:43)
        at com.pinterest.ktlint.core.internal.KotlinPsiFileFactoryProvider.getKotlinPsiFileFactory(KotlinPsiFileFactory.kt:35)
        at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:393)
        at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:382)
        at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:354)
        at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:350)
        at org.jmailen.gradle.kotlinter.tasks.format.FormatWorkerAction.format(FormatWorkerAction.kt:78)
        at org.jmailen.gradle.kotlinter.tasks.format.FormatWorkerAction.formatKt(FormatWorkerAction.kt:72)
        at org.jmailen.gradle.kotlinter.tasks.format.FormatWorkerAction.access$formatKt(FormatWorkerAction.kt:19)
        at org.jmailen.gradle.kotlinter.tasks.format.FormatWorkerAction$execute$1$1.invoke(FormatWorkerAction.kt:38)
        at org.jmailen.gradle.kotlinter.tasks.format.FormatWorkerAction$execute$1$1.invoke(FormatWorkerAction.kt:19)
        at org.jmailen.gradle.kotlinter.tasks.format.FormatWorkerAction.execute(FormatWorkerAction.kt:45)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
        at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:205)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:187)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:120)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:162)
        at org.gradle.internal.Factories$1.create(Factories.java:31)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
        at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
        at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:114)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:157)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:126)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Also reported at https://github.com/jeremymailen/kotlinter-gradle/issues/254

**Comment by paul-dingemans** [comment]
I have never seen this message. Please describe how to reproduce.

**Comment by henrik242** [comment]
This project is huge, so I need to figure out how to reproduce in a smaller one.  @jeremymailen [hints to a similar issue](https://github.com/jeremymailen/kotlinter-gradle/issues/254#issuecomment-1164056093), though.

**Comment by paul-dingemans** [comment]
Closed because lack of reproduction path. Feel free to reopen once you know how to reproduce the problem.
