### ISSUE TITLE
`--relative` and `--reporter=sarif` don't play well together

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [pinterest/ktlint#1608]
## Expected Behavior

It should be possible to request relative paths in SARIF-reporting mode.

## Observed Behavior

Running

```bash
java -Xmx512m --add-opens java.base/java.lang=ALL-UNNAMED -jar ktlint --reporter=sarif --relative
```

results in 

```console
17:27:53.895 [pool-1-thread-1] ERROR org.cqfn.diktat.ruleset.rules.chapter1.PackageNaming - Not able to determine a path to a scanned file or "src" directory cannot be found in it's path. Will not be able to determine correct package name. It can happen due to missing <src> directory in the path
Exception in thread "main" java.lang.IllegalArgumentException: this and base files have different roots: C.kt and /home/alice.
        at kotlin.io.FilesKt__UtilsKt.toRelativeString(Utils.kt:117)
        at kotlin.io.FilesKt__UtilsKt.relativeTo(Utils.kt:128)
        at com.pinterest.ktlint.reporter.sarif.SarifReporter.onLintError(SarifReporter.kt:52)
        at com.pinterest.ktlint.core.Reporter$Companion$from$1.onLintError(Reporter.kt:53)
        at com.pinterest.ktlint.internal.KtlintCommandLine.report(KtlintCommandLine.kt:355)
        at com.pinterest.ktlint.internal.KtlintCommandLine.access$report(KtlintCommandLine.kt:52)
        at com.pinterest.ktlint.internal.KtlintCommandLine$lintFiles$4.invoke(KtlintCommandLine.kt:321)
        at com.pinterest.ktlint.internal.KtlintCommandLine$lintFiles$4.invoke(KtlintCommandLine.kt:321)
        at com.pinterest.ktlint.internal.KtlintCommandLine.parallel(KtlintCommandLine.kt:605)
        at com.pinterest.ktlint.internal.KtlintCommandLine.parallel$default(KtlintCommandLine.kt:563)
        at com.pinterest.ktlint.internal.KtlintCommandLine.lintFiles(KtlintCommandLine.kt:321)
        at com.pinterest.ktlint.internal.KtlintCommandLine.run(KtlintCommandLine.kt:268)
        at com.pinterest.ktlint.Main.main(Main.kt:27)
```

## Steps to Reproduce

1. Download the latest fat JAR from the _Releases_ page and make it executable (`chmod 755`). Version **0.46.1** is also affected.
2. Place a single Kotlin file (e.g.: `C.kt`) into the same directory as the `ktlint` executable. Make sure your code produces at least one `ktlint` warning, e. g.:
   ```kotlin
   class C{}
   ```
4. Run `ktlint` as 
   ```bash
   ./ktlint --relative --reporter=sarif
   ```
   or
   ```bash
   ./ktlint --relative --reporter=sarif C.kt
   ```
5. The error message is misleading: it doesn't actually matter whether the file resides _inside_ or _outside_ the user's home directory, or whether an absolute or a relative path is passed to `ktlint`.

## Your Environment
* Version of ktlint used: **0.46.1** and **0.47.0**
* Integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): **CLI**
* Operating System and version: **any** (Linux, Cygwin, WSL).

**Comment by 0x6675636b796f75676974687562** [comment]
### Update

The `--relative` mode is not even necessary. This is what I've just received when running `ktlint` on Windows:

```console
D:\>java -Xmx512m --add-opens java.base/java.lang=ALL-UNNAMED -jar ktlint --reporter=sarif C.kt
Exception in thread "main" java.lang.IllegalArgumentException: this and base files have different roots: D:\C.kt and C:\Users\Administrator.
        at kotlin.io.FilesKt__UtilsKt.toRelativeString(Utils.kt:117)
        at kotlin.io.FilesKt__UtilsKt.relativeTo(Utils.kt:128)
        at com.pinterest.ktlint.reporter.sarif.SarifReporter.onLintError(SarifReporter.kt:52)
        at com.pinterest.ktlint.core.Reporter$Companion$from$1.onLintError(Reporter.kt:53)
        at com.pinterest.ktlint.internal.KtlintCommandLine.report(KtlintCommandLine.kt:355)
        at com.pinterest.ktlint.internal.KtlintCommandLine.access$report(KtlintCommandLine.kt:52)
        at com.pinterest.ktlint.internal.KtlintCommandLine$lintFiles$4.invoke(KtlintCommandLine.kt:321)
        at com.pinterest.ktlint.internal.KtlintCommandLine$lintFiles$4.invoke(KtlintCommandLine.kt:321)
        at com.pinterest.ktlint.internal.KtlintCommandLine.parallel(KtlintCommandLine.kt:605)
        at com.pinterest.ktlint.internal.KtlintCommandLine.parallel$default(KtlintCommandLine.kt:563)
        at com.pinterest.ktlint.internal.KtlintCommandLine.lintFiles(KtlintCommandLine.kt:321)
        at com.pinterest.ktlint.internal.KtlintCommandLine.run(KtlintCommandLine.kt:268)
        at com.pinterest.ktlint.Main.main(Main.kt:27)
```

**Comment by paul-dingemans** [comment]
Sarif has been introduced in ktlint 0.42. Already since that first version in which it was introduced, this error exists. Without the `--relative` parameter it does work for me on Linux on all versions. I expect that your remark about the error also occuring without `--relative` is related to problems on the Windows filesystem introduced by ktlint 0.47. But that would only hold true in case 0.46.1 on windows, without `--relative` does *not* cause the error.

**Comment by 0x6675636b796f75676974687562** [comment]
@paul-dingemans, yes indeed, the offending line comes from #1113, commit bfc0805bc52727ab26e3c8be946a01ee844a45ef.

Yet, there's a clear problem with the code:

```kotlin
                                    uri = File(file).relativeTo(workingDirectory).path,
```

For some reason, `workingDirectory` is always set to the user's home and not the project/current directory. Your users have to explicitly run `java` with `-Duser.home=...` to work this around.

Second, the `IAE` (which is clearly documented in the API and may well get thrown) is not accounted for.

And third, the `File` object is relativized against the "project directory" w/o being first converted to an absolute path (which is nonsense).

Unfortunately, there's no integration tests to account for all the remarks I've just made.

**Comment by 0x6675636b796f75676974687562** [comment]
@paul-dingemans, here're the test results.

As you can see, to work the problem around, the user has

1. override `user.home` (e.g.: `java "-Duser.home=$(pwd)" -jar ktlint ...`), and
2. avoid using `--relative` command line switch.

| Command                              | Input                                                       | `user.home` overridden | Outcome                                                                               |
|--------------------------------------|-------------------------------------------------------------|------------------------|---------------------------------------------------------------------------------------|
| `ktlint --reporter=sarif`            | None (`ktlint` recursively traverses the current directory) | :x: (default)          | SARIF with wrong `%SRCROOT%` and paths (**incorrectly**) relativized w.r.t. `${HOME}` |
| `ktlint --reporter=sarif`            | `**/*.kt` (an _Ant_ path pattern)                           | :x: (default)          | SARIF with wrong `%SRCROOT%` and paths (**incorrectly**) relativized w.r.t. `${HOME}` |
| `ktlint --reporter=sarif`            | `C.kt` (the name of the file in the current directory)      | :x: (default)          | SARIF with wrong `%SRCROOT%` and paths (**incorrectly**) relativized w.r.t. `${HOME}` |
| `ktlint --reporter=sarif`            | `./C.kt` (a relative path)                                  | :x: (default)          | SARIF with wrong `%SRCROOT%` and paths (**incorrectly**) relativized w.r.t. `${HOME}` |
| `ktlint --reporter=sarif`            | `/path/to/C.kt` (an absolute path)                          | :x: (default)          | SARIF with wrong `%SRCROOT%` and paths (**incorrectly**) relativized w.r.t. `${HOME}` |
| `ktlint --reporter=sarif`            | None (`ktlint` recursively traverses the current directory) | :heavy_check_mark:     | SARIF with correct relative paths                                                     |
| `ktlint --reporter=sarif`            | `**/*.kt` (an _Ant_ path pattern)                           | :heavy_check_mark:     | SARIF with correct relative paths                                                     |
| `ktlint --reporter=sarif`            | `C.kt` (the name of the file in the current directory)      | :heavy_check_mark:     | SARIF with correct relative paths                                                     |
| `ktlint --reporter=sarif`            | `./C.kt` (a relative path)                                  | :heavy_check_mark:     | SARIF with correct relative paths                                                     |
| `ktlint --reporter=sarif`            | `/path/to/C.kt` (an absolute path)                          | :heavy_check_mark:     | SARIF with correct relative paths                                                     |
| `ktlint --reporter=sarif --relative` | None (`ktlint` recursively traverses the current directory) | :x: (default)          | **Exception**                                                                         |
| `ktlint --reporter=sarif --relative` | `**/*.kt` (an _Ant_ path pattern)                           | :x: (default)          | **Exception**                                                                         |
| `ktlint --reporter=sarif --relative` | `C.kt` (the name of the file in the current directory)      | :x: (default)          | **Exception**                                                                         |
| `ktlint --reporter=sarif --relative` | `./C.kt` (a relative path)                                  | :x: (default)          | **Exception**                                                                         |
| `ktlint --reporter=sarif --relative` | `/path/to/C.kt` (an absolute path)                          | :x: (default)          | **Exception**                                                                         |
| `ktlint --reporter=sarif --relative` | None (`ktlint` recursively traverses the current directory) | :heavy_check_mark:     | **Exception**                                                                         |
| `ktlint --reporter=sarif --relative` | `**/*.kt` (an _Ant_ path pattern)                           | :heavy_check_mark:     | **Exception**                                                                         |
| `ktlint --reporter=sarif --relative` | `C.kt` (the name of the file in the current directory)      | :heavy_check_mark:     | **Exception**                                                                         |
| `ktlint --reporter=sarif --relative` | `./C.kt` (a relative path)                                  | :heavy_check_mark:     | **Exception**                                                                         |
| `ktlint --reporter=sarif --relative` | `/path/to/C.kt` (an absolute path)                          | :heavy_check_mark:     | **Exception**                                                                         |

**Comment by paul-dingemans** [comment]
Tnx for testing and report back so extensively. Clearly, it is not a good user experience if the user has to work around the problem like you described:
> As you can see, to work the problem around, the user has to
> 
> override user.home (e.g.: java "-Duser.home=$(pwd)" -jar ktlint ...), and
> avoid using --relative command line switch

This needs to be addressed in a future release. For me, it has no high priority yet compared to other issues that I want to pick up.

**Comment by 0x6675636b796f75676974687562** [comment]
Hello @paul-dingemans.

Was playing with Ktlint 0.47.1 and found yet another manifestation of this (while running plain `java -jar ktlint`):

```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: 'other' has different root
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.pinterest.ktlint.internal.KtlintCommandLine.parallel(KtlintCommandLine.kt:606)
	at com.pinterest.ktlint.internal.KtlintCommandLine.parallel$default(KtlintCommandLine.kt:564)
	at com.pinterest.ktlint.internal.KtlintCommandLine.lintFiles(KtlintCommandLine.kt:322)
	at com.pinterest.ktlint.internal.KtlintCommandLine.run(KtlintCommandLine.kt:268)
	at com.pinterest.ktlint.Main.main(Main.kt:27)
Caused by: java.lang.IllegalArgumentException: 'other' has different root
	at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:392)
	at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:44)
	at com.pinterest.ktlint.core.api.BaselineKt.getRelativeRoute(Baseline.kt:152)
	at com.pinterest.ktlint.internal.KtlintCommandLine$lintFiles$3.invoke$lambda-0(KtlintCommandLine.kt:318)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

The good news the issue is Windows-specific.

The bad news is the codebase seems to plagued with it -- basically, all calls to `Path.relativize()` need to wrapped into either a check or a try-catch block.

**Comment by paul-dingemans** [comment]
Hi @0x6675636b796f75676974687562 

> The bad news is the codebase seems to plagued with it -- basically, all calls to Path.relativize() need to wrapped into either a check or a try-catch block.

It would be nice if you had checked out the KtLint codebase before the statement above or if you would have avoided the term `plagued`. The entire codebase of KtLint contains 4 `relavitize` statement of which 50% occur in tests only. And indeed, none of them are guarded for safe use on Windows which make this a valid bug. KtLint is free software, maintained by volunteers and the statement might be felt as offensive (at least it does a little as far as I am concerned).

**Comment by 0x6675636b796f75676974687562** [comment]
Apologies @paul-dingemans, didn't mean to sound rude or offensive.

KtLint is an amazing tool &mdash; it's rather my own disappointment that I am not familiar enough with the code base and cannot quickly fix the problem.

I've created a PR (#1686) that aims to at least work around the problem.
Please review once you have a minute.

**Comment by paul-dingemans** [comment]
> Apologies @paul-dingemans, didn't mean to sound rude or offensive.

Thanks, I appreciate it.

> I've created a PR (https://github.com/pinterest/ktlint/pull/1686) that aims to at least work around the problem.
Please review once you have a minute.

Done

**Comment by 0x6675636b796f75676974687562** [comment]
Hi @paul-dingemans.

Thanks for merging #1686.
Probaqbly this issue can be closed now, can't it?

**Comment by paul-dingemans** [comment]
> Hi @paul-dingemans.
> 
> Thanks for merging #1686. Probaqbly this issue can be closed now, can't it?

I did not close it as the description of #1686 mentioned that it closes this issue partially. As you are the original poster of this issue, I think you can best decided whether it actually is completed or not.

**Comment by 0x6675636b796f75676974687562** [comment]
@paul-dingemans, I believe we can safely close this issue.

I will either report a new one or re-open should the problem reoccur.
