### ISSUE TITLE
applyToIDEA not found

### ISSUE THREAD

**Issue by MathiasOhrstrom** [pinterest/ktlint#1715]
## Expected Behavior

Apply ktlint formatting style guidelines to android studio

## Observed Behavior

When i run `ktlint applyToIDEA --log-level=debug` i get this 
```
Exception in thread "main" picocli.CommandLine$UnmatchedArgumentException: Unknown option: '--log-level=debug'
        at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13248)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:13200)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:13146)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:13047)
        at picocli.CommandLine.parseArgs(CommandLine.java:1478)
        at com.pinterest.ktlint.Main.main(Main.kt:20)
```

When running `ktlint applyToIDEA` i get ` [main] WARN com.pinterest.ktlint.internal.KtlintCommandLine - No files matched [applyToIDEA]`

## Steps to Reproduce
Run `ktlint applyToIDEA` to see the error.
Or run `ktlint -h` to see that the applyToIDEA and applyToIDEAProject options are no longer there

## Your Environment
* Version of ktlint used: 0.47.1
* Operating System and version: Mac os Version 13.0.1

**Comment by paul-dingemans** [comment]
The command `applyToIDEA` has been removed as part of #1570.
