### ISSUE TITLE
ktlint should not fall over if ij_java_packages_to_use_import_on_demand or ij_kotlin_packages_to_use_import_on_demand is blank in .editorConfig

### ISSUE THREAD

**Issue by kenyee** [pinterest/ktlint#2046]
## Expected Behavior
Should be alllowed to set these to blank if we don't want any packages to use import on demand

## Observed Behavior
ktlint throws these exceptions:
```
Exception in thread "main" java.util.concurrent.ExecutionException: org.ec4j.core.parser.ParseException: path:/Users/keny/work/samurai/.editorconfig:18:45: Property 'ij_kotlin_packages_to_use_import_on_demand' has no value
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.pinterest.ktlint.internal.KtlintCommandLine.parallel(KtlintCommandLine.kt:578)
        at com.pinterest.ktlint.internal.KtlintCommandLine.parallel$default(KtlintCommandLine.kt:536)
        at com.pinterest.ktlint.internal.KtlintCommandLine.lintFiles(KtlintCommandLine.kt:283)
        at com.pinterest.ktlint.internal.KtlintCommandLine.run(KtlintCommandLine.kt:235)
        at com.pinterest.ktlint.Main.main(Main.kt:31)
Caused by: org.ec4j.core.parser.ParseException: path:/Users/keny/work/samurai/.editorconfig:18:45: Property 'ij_kotlin_packages_to_use_import_on_demand' has no value
```

and

```
Exception in thread "main" java.util.concurrent.ExecutionException: org.ec4j.core.parser.ParseException: path:/Users/keny/work/samurai/.editorconfig:13:43: Property 'ij_java_packages_to_use_import_on_demand' has no value
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.pinterest.ktlint.internal.KtlintCommandLine.parallel(KtlintCommandLine.kt:578)
        at com.pinterest.ktlint.internal.KtlintCommandLine.parallel$default(KtlintCommandLine.kt:536)
        at com.pinterest.ktlint.internal.KtlintCommandLine.lintFiles(KtlintCommandLine.kt:283)
        at com.pinterest.ktlint.internal.KtlintCommandLine.run(KtlintCommandLine.kt:235)
        at com.pinterest.ktlint.Main.main(Main.kt:31)
Caused by: org.ec4j.core.parser.ParseException: path:/Users/keny/work/samurai/.editorconfig:13:43: Property 'ij_java_packages_to_use_import_on_demand' has no value

```

This also causes it to write a 0 length XML report.

## Steps to Reproduce
Add these properties to your .editorConfig with no value.
Run ktlint

## Your Environment
* Version of ktlint used: 0.46.1
* Relevant parts of the `.editorconfig` settings
ij_kotlin_packages_to_use_import_on_demand=
ij_java_packages_to_use_import_on_demand=
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task):
```
tasks.register("ktlint", JavaExec) {
    group = "verification"
    description = "Check Kotlin code style."
    classpath = configurations.ktlint
    main = "com.pinterest.ktlint.Main"
    args "src/**/*.kt", "--reporter=plain", "--reporter=checkstyle,output=${buildDir}/ktlint.xml", "--android"
    ignoreExitValue = true
    // see https://github.com/pinterest/ktlint#usage for more
}
```
* Version of Gradle used (if applicable): 8.1.1
* Operating System and version: OSX Ventura

**Comment by paul-dingemans** [comment]
Please consult documentation: https://pinterest.github.io/ktlint/0.49.1/rules/standard/#no-wildcard-imports and use `unset` instead of a blank value.

**Comment by kenyee** [comment]
Thanks Paul...should have searched the docs :-( 
That seems like an odd thing (i.e., less intuitive) to do instead of using a blank value...or using a blank value as an alternative to "unset".  Any context on why it uses "unset"?

**Comment by kenyee** [comment]
hmmm..because it's part of the .editorConfig spec?
https://editorconfig.org/

**Comment by kenyee** [comment]
Though it says:
"For any property, a value of unset is to remove the effect of that property, even if it has been set before. For example, add indent_size = unset to undefine indent_size property (and use editor default)."
which isn't necessarily "no values"...just clear it.

**Comment by paul-dingemans** [comment]
The reason behind this behavior is some compatibility reason with the default IntelliJ IDEA formatter. Inside the IntelliJ IDEA formatter this property is defined to have a certain value whenever it is not set. To mimic that behavior, the property is defined in Ktlint with an explicit default value. By using. `unset` the default value set by Ktlint is undone *and* it also means that IntelliJ IDEA formatter works as expected.

**Comment by kenyee** [comment]
Thanks for the additional context :-)
