### ISSUE TITLE
Gradle java task: java.lang.ClassNotFoundException: io.github.oshai.kotlinlogging.KLogger

### ISSUE THREAD

**Issue by cowst** [pinterest/ktlint#2247]
## Expected Behavior
I just moved from 0.50.0 to 1.0.0, and I am trying to call ktlint as I did so far, for example to check the code.

## Observed Behavior
With 1.0.0 commands are throwing an exception.

## Steps to Reproduce
Create this task in Gradle
```
configurations {
    ktlint {
        attributes {
            attribute(Bundling.BUNDLING_ATTRIBUTE, objects.named(Bundling, Bundling.EXTERNAL))
        }
    }
}

tasks.register("ktlintCheck", JavaExec) {
    description = "Check Kotlin code style."
    group = "verification"
    classpath = configurations.ktlint
    mainClass.set("com.pinterest.ktlint.Main")
}
```
when calling it, it throws the following:
`
> Task :ktlintCheck FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: io/github/oshai/kotlinlogging/KLogger
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at picocli.CommandLine.getCommandMethods(CommandLine.java:3329)
	at picocli.CommandLine.access$2800(CommandLine.java:148)
	at picocli.CommandLine$Model$CommandSpec.createMethodSubcommands(CommandLine.java:6742)
	at picocli.CommandLine$Model$CommandReflection.initMethodSubcommands(CommandLine.java:11894)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11845)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6388)
	at picocli.CommandLine.<init>(CommandLine.java:230)
	at picocli.CommandLine.<init>(CommandLine.java:224)
	at picocli.CommandLine.<init>(CommandLine.java:199)
	at com.pinterest.ktlint.Main.main(Main.kt:18)
Caused by: java.lang.ClassNotFoundException: io.github.oshai.kotlinlogging.KLogger
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 13 more

`

## Your Environment
* Version of ktlint used: 1.0.0
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): custom Gradle task posted above
* Version of Gradle used (if applicable): 8.0.2
* Operating System and version: macOS Ventura 13.5.1
* java 17
* kotlin 1.9.0

**Comment by paul-dingemans** [comment]
Your configuration above does not show the dependencies that you have used. For me, configuration below works:
```
repositories {
    mavenCentral()
}

configurations {
    ktlint
}

dependencies {
    ktlint("com.pinterest.ktlint:ktlint-cli:1.0.0"){
        attributes {
            attribute(Bundling.BUNDLING_ATTRIBUTE, getObjects().named(Bundling, Bundling.EXTERNAL))
        }
    }
}

tasks.register("ktlint", JavaExec) {
    group = "verification"
    description = "Check Kotlin code style."
    classpath = configurations.ktlint
    mainClass = "com.pinterest.ktlint.Main"
    // see https://pinterest.github.io/ktlint/install/cli/#command-line-usage for more information
    args "src/**/*.kt", "**.kts", "!**/build/**"
}
```

**Comment by cowst** [comment]
Hi, thanks for the help.
Here is a follow up for your post.

dependencies in toml:
```
ktlint = "1.0.0"
ktlint = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }
```

and in build.gradle:
```
dependencies {
    ktlint(libs.ktlint)
}
```

I moved the attributes as you did, and now I get:
```
> Task :ktlintCheck
09:06:27.686 [main] INFO com.pinterest.ktlint.cli.internal.KtlintCommandLine - Enable default patterns [**/*.kt, **/*.kts]
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Skipping rule(s) which are depending on a rule which is not loaded. Please check if you need to add additional rule sets before creating an issue.
  - Rule with id 'RuleId(value=standard:chain-method-continuation)' requires rule with id 'RuleId(value=standard:discouraged-comment-location)' to be loaded
  - Rule with id 'RuleId(value=standard:chain-method-continuation)' requires rule with id 'RuleId(value=standard:argument-list-wrapping)' to be loaded
  - Rule with id 'RuleId(value=standard:class-signature)' requires rule with id 'RuleId(value=standard:discouraged-comment-location)' to be loaded
  - Rule with id 'RuleId(value=standard:if-else-wrapping)' requires rule with id 'RuleId(value=standard:discouraged-comment-location)' to be loaded
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.pinterest.ktlint.cli.internal.KtlintCommandLine.parallel(KtlintCommandLine.kt:688)
	at com.pinterest.ktlint.cli.internal.KtlintCommandLine.parallel$default(KtlintCommandLine.kt:651)
	at com.pinterest.ktlint.cli.internal.KtlintCommandLine.lintFiles(KtlintCommandLine.kt:423)
	at com.pinterest.ktlint.cli.internal.KtlintCommandLine.run(KtlintCommandLine.kt:303)
	at com.pinterest.ktlint.Main.main(Main.kt:35)
Caused by: java.lang.IllegalStateException: Skipping rule(s) which are depending on a rule which is not loaded. Please check if you need to add additional rule sets before creating an issue.
  - Rule with id 'RuleId(value=standard:chain-method-continuation)' requires rule with id 'RuleId(value=standard:discouraged-comment-location)' to be loaded
  - Rule with id 'RuleId(value=standard:chain-method-continuation)' requires rule with id 'RuleId(value=standard:argument-list-wrapping)' to be loaded
  - Rule with id 'RuleId(value=standard:class-signature)' requires rule with id 'RuleId(value=standard:discouraged-comment-location)' to be loaded
  - Rule with id 'RuleId(value=standard:if-else-wrapping)' requires rule with id 'RuleId(value=standard:discouraged-comment-location)' to be loaded
	at com.pinterest.ktlint.rule.engine.internal.rulefilter.RunAfterRuleFilter.filter(RunAfterRuleFilter.kt:77)
	at com.pinterest.ktlint.rule.engine.internal.rulefilter.RuleFilterKt.applyRuleFilters(RuleFilter.kt:15)
	at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$Companion.createRuleExecutionContext$ktlint_rule_engine(RuleExecutionContext.kt:192)
	at com.pinterest.ktlint.rule.engine.api.KtLintRuleEngine.lint(KtLintRuleEngine.kt:94)
	at com.pinterest.ktlint.cli.internal.KtlintCommandLine.lint(KtlintCommandLine.kt:548)
	at com.pinterest.ktlint.cli.internal.KtlintCommandLine.process(KtlintCommandLine.kt:473)
	at com.pinterest.ktlint.cli.internal.KtlintCommandLine.access$process(KtlintCommandLine.kt:59)
	at com.pinterest.ktlint.cli.internal.KtlintCommandLine$lintFiles$3.invoke$lambda$0(KtlintCommandLine.kt:411)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I would not want/need to pass args to change the default file patterns to check (I tried and made no difference, btw).

my .editorconfig (before 1.0.0 bump, I was on 0.50.0):
```
[*.{kt,kts}]
max_line_length=150
ij_kotlin_imports_layout=*
ij_kotlin_packages_to_use_import_on_demand=TensorFlowLiteC.*,java.util.*

ktlint_standard=enabled
ktlint_standard_filename=disabled
ktlint_standard_property-naming=disabled
ktlint_standard_function-naming=disabled
ktlint_standard_comment-wrapping=disabled
ktlint_standard_wrapping=disabled
ktlint_standard_enum-entry-name-case=disabled
ktlint_standard_multiline-if-else=disabled
ktlint_standard_trailing-comma-on-call-site=disabled
ktlint_standard_trailing-comma-on-declaration-site=disabled
ktlint_standard_argument-list-wrapping=disabled
ktlint_standard_function-signature=disabled

ktlint_experimental=enabled
ktlint_standard_enum-wrapping=disabled
ktlint_standard_discouraged-comment-location=disabled
ktlint_standard_no-empty-file=disabled
```

I will try to play around with the new rules and see if I can make it happy, however I wonder if those skipping rules above should be a warning rather than a blocking error.

**Comment by cowst** [comment]
ok, problem solved, still don't like too much the error vs the warning :)

**Comment by paul-dingemans** [comment]
> I will try to play around with the new rules and see if I can make it happy, however I wonder if those skipping rules above should be a warning rather than a blocking error.

The reason for making it blocking is simply to reduce complexity in the rules. It is nearly impossible to support every combination of sets of rules that are enabled/disabled. By enforcing a certain rule to be enabled, the rule which depend on that rule can just assume that certain things will never happen as they will be resolved by that rule.

Ideally, you stick to the defaults set by the code style. Once you start disabling rules, you are already bike-shedding. The idea of ktlint is avoiding bike-shedding by providing a complete and integrated set of rules and default settings. Configuration is possible, within limits.

**Comment by cowst** [comment]
Fair enough :)
