### ISSUE TITLE
KtLint inspects excluded files

### ISSUE THREAD

**Issue by vRallev** [pinterest/ktlint#2272]
We configure a KtLint task like this:
```
tasks.register("ktlint", JavaExec::class.java) {
  it.description = "Check Kotlin code style."
  it.classpath(ktlintConfig)
  it.mainClass.set("com.pinterest.ktlint.Main")
  it.args("src/**/*.kt")
}
```

Randomly we see this error:
```
Exception in thread "main" java.nio.file.NoSuchFileException: /local/p4clients/{module}/build/intermediates/verified_library_resources/release/linked.apk
    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
    at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
    at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
    at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
    at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
    at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
    at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:374)
    at java.base/java.nio.file.Files.walkFileTree(Files.java:2845)
    at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
    at com.pinterest.ktlint.cli.internal.FileUtilsKt.fileSequence(FileUtils.kt:102)
    at com.pinterest.ktlint.cli.internal.FileUtilsKt.fileSequence$default(FileUtils.kt:39)
    at com.pinterest.ktlint.cli.internal.KtlintCommandLine.lintFiles(KtlintCommandLine.kt:405)
    at com.pinterest.ktlint.cli.internal.KtlintCommandLine.run(KtlintCommandLine.kt:312)
    at com.pinterest.ktlint.Main.main(Main.kt:35)
```
It is not clear at all, why KtLint looks at files in the `build` directory of the same module even though we configured it to look at the `src` directory only. It shouldn't look at .apk files either and only read .kt files.

Because of this bug, we tried following configuration. But it didn't make any difference.
```
tasks.register("ktlint", JavaExec::class.java) {
  it.description = "Check Kotlin code style."
  it.classpath(ktlintConfig)
  it.mainClass.set("com.pinterest.ktlint.Main")
  it.args("!build/**")
  it.args("src/**/*.kt")
}
```

Unfortunately, this issue happens randomly and we can't reproduce it. We see it mostly in CI on Linux machines. 
```
Gradle 8.0.2
Kotlin:       1.8.10
Groovy:       3.0.13
JVM:          17.0.8 (Amazon.com Inc. 17.0.8+9-LTS)
KtLint: 0.50.0
```

**Comment by paul-dingemans** [comment]
You're right that ktlint should never pickup a file like `linked.apk`. This means that the include/exclude patterns are not processed correctly. 

Please try changing `it.args("!build/**")` to `it.args("!**/build/**")`. See [Groovy integration](https://pinterest.github.io/ktlint/1.0.0/install/integrations/#custom-gradle-integration-with-groovy) or [Kotlin integration](https://pinterest.github.io/ktlint/1.0.0/install/integrations/#custom-gradle-integration-with-kotlin-dsl)

**Comment by vRallev** [comment]
Thank you, I'll give this a try. I'm okay with closing this issue for now and I can reopen it in case we see the issue again. It can also stay open for a while. Whatever you prefer.

**Comment by paul-dingemans** [comment]
You can also force the issue. Just add a file with a violation on a new path, and exclude that specific path in the ktlint parameters. The new file with the violation should not break your build.

**Comment by vRallev** [comment]
I tried doing this with .apk file from the error and was not able to reproduce the bug locally.

**Comment by paul-dingemans** [comment]
Ok, lets close the issue then. Feel free to reopen when it appears again.
