### ISSUE TITLE
Rule with id 'RuleId(value=standard:string-template-indent)' requires rule with id 'RuleId(value=standard:indent)' to be loaded

### ISSUE THREAD

**Issue by dmitry-weirdo** [pinterest/ktlint#2325]
After updating ktlint from `0.50.0` → to `0.51.0-FINAL`, the following starts to fail while running Ktlint via `maven-antrun-plugin`:

```
[INFO]    [ktlint] Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Skipping rule(s) which are depending on a rule which is not loaded. Please check if you need to add additional rule sets before creating an issue.
[INFO]    [ktlint]   - Rule with id 'RuleId(value=standard:string-template-indent)' requires rule with id 'RuleId(value=standard:indent)' to be loaded
[INFO]    [ktlint] 	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[INFO]    [ktlint] 	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[INFO]    [ktlint] 	at com.pinterest.ktlint.cli.internal.KtlintCommandLine.parallel(KtlintCommandLine.kt:688)
[INFO]    [ktlint] 	at com.pinterest.ktlint.cli.internal.KtlintCommandLine.parallel$default(KtlintCommandLine.kt:651)
[INFO]    [ktlint] 	at com.pinterest.ktlint.cli.internal.KtlintCommandLine.lintFiles(KtlintCommandLine.kt:423)
[INFO]    [ktlint] 	at com.pinterest.ktlint.cli.internal.KtlintCommandLine.run(KtlintCommandLine.kt:303)
[INFO]    [ktlint] 	at com.pinterest.ktlint.Main.main(Main.kt:35)
[INFO]    [ktlint] Caused by: java.lang.IllegalStateException: Skipping rule(s) which are depending on a rule which is not loaded. Please check if you need to add additional rule sets before creating an issue.
[INFO]    [ktlint]   - Rule with id 'RuleId(value=standard:string-template-indent)' requires rule with id 'RuleId(value=standard:indent)' to be loaded
[INFO]    [ktlint] 	at com.pinterest.ktlint.rule.engine.internal.rulefilter.RunAfterRuleFilter.filter(RunAfterRuleFilter.kt:77)
[INFO]    [ktlint] 	at com.pinterest.ktlint.rule.engine.internal.rulefilter.RuleFilterKt.applyRuleFilters(RuleFilter.kt:15)
[INFO]    [ktlint] 	at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$Companion.createRuleExecutionContext$ktlint_rule_engine(RuleExecutionContext.kt:192)
[INFO]    [ktlint] 	at com.pinterest.ktlint.rule.engine.api.KtLintRuleEngine.lint(KtLintRuleEngine.kt:94)
[INFO]    [ktlint] 	at com.pinterest.ktlint.cli.internal.KtlintCommandLine.lint(KtlintCommandLine.kt:548)
[INFO]    [ktlint] 	at com.pinterest.ktlint.cli.internal.KtlintCommandLine.process(KtlintCommandLine.kt:473)
[INFO]    [ktlint] 	at com.pinterest.ktlint.cli.internal.KtlintCommandLine.access$process(KtlintCommandLine.kt:59)
[INFO]    [ktlint] 	at com.pinterest.ktlint.cli.internal.KtlintCommandLine$lintFiles$3.invoke$lambda$0(KtlintCommandLine.kt:411)
[INFO]    [ktlint] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[INFO]    [ktlint] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[INFO]    [ktlint] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[INFO]    [ktlint] 	at java.base/java.lang.Thread.run(Thread.java:833)
[INFO] ------------------------------------------------------------------------
```

Notably, there is no `string-template-indent` in our `.editorconfig`, just these rule related to indentation are present:

```
[{*.kt,*.kts}]
indent_size = 4
tab_width = 4
ij_kotlin_imports_layout = *,java.**,javax.**,kotlin.**,^

# although shown as incorrect in IDEA, these rule-per-rule disables are actually working.
# see https://pinterest.github.io/ktlint/rules/configuration-ktlint/#disabled-rules
ktlint_ignore_back_ticked_identifier = false
ktlint_standard_indent = disabled

# allow multiple annotations on one line (like @Valid @RequestBody value)
ktlint_standard_annotation = disabled
```

If I add the explicit disable of this rule:
```
# disable the failing rule after updating to 0.51.0-FINAL
# see https://pinterest.github.io/ktlint/0.49.1/rules/experimental/
# see https://pinterest.github.io/ktlint/1.0.1/rules/standard/#string-template-indent
ktlint_string_template_indent = disabled
```

It is a different failure but with the same reason:
```
[INFO] --- maven-antrun-plugin:3.1.0:run (ktlint) @ rcs ---
[INFO] Executing tasks
[INFO]    [ktlint] Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Skipping rule(s) which are depending on a rule which is not loaded. Please check if you need to add additional rule sets before creating an issue.
[INFO]    [ktlint]   - Rule with id 'RuleId(value=standard:string-template-indent)' requires rule with id 'RuleId(value=standard:indent)' to be loaded
[INFO]    [ktlint]      at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
[INFO]    [ktlint]      at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
[INFO]    [ktlint]      at com.pinterest.ktlint.cli.internal.KtlintCommandLine.parallel(KtlintCommandLine.kt:688)
[INFO]    [ktlint]      at com.pinterest.ktlint.cli.internal.KtlintCommandLine.parallel$default(KtlintCommandLine.kt:651)
[INFO]    [ktlint]      at com.pinterest.ktlint.cli.internal.KtlintCommandLine.lintFiles(KtlintCommandLine.kt:423)
[INFO]    [ktlint]      at com.pinterest.ktlint.cli.internal.KtlintCommandLine.run(KtlintCommandLine.kt:303)
[INFO]    [ktlint]      at com.pinterest.ktlint.Main.main(Main.kt:35)
[INFO]    [ktlint] Caused by: java.lang.IllegalStateException: Skipping rule(s) which are depending on a rule which is not loaded. Please check if you need to add additional rule sets before creating an issue.
[INFO]    [ktlint]   - Rule with id 'RuleId(value=standard:string-template-indent)' requires rule with id 'RuleId(value=standard:indent)' to be loaded
[INFO]    [ktlint]      at com.pinterest.ktlint.rule.engine.internal.rulefilter.RunAfterRuleFilter.filter(RunAfterRuleFilter.kt:77)
[INFO]    [ktlint]      at com.pinterest.ktlint.rule.engine.internal.rulefilter.RuleFilterKt.applyRuleFilters(RuleFilter.kt:15)
[INFO]    [ktlint]      at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$Companion.createRuleExecutionContext$ktlint_rule_engine(RuleExecutionContext.kt:192)
[INFO]    [ktlint]      at com.pinterest.ktlint.rule.engine.api.KtLintRuleEngine.lint(KtLintRuleEngine.kt:94)
[INFO]    [ktlint]      at com.pinterest.ktlint.cli.internal.KtlintCommandLine.lint(KtlintCommandLine.kt:548)
[INFO]    [ktlint]      at com.pinterest.ktlint.cli.internal.KtlintCommandLine.process(KtlintCommandLine.kt:473)
[INFO]    [ktlint]      at com.pinterest.ktlint.cli.internal.KtlintCommandLine.access$process(KtlintCommandLine.kt:59)
[INFO]    [ktlint]      at com.pinterest.ktlint.cli.internal.KtlintCommandLine$lintFiles$3.invoke$lambda$0(KtlintCommandLine.kt:411)
[INFO]    [ktlint]      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[INFO]    [ktlint]      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[INFO]    [ktlint]      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[INFO]    [ktlint]      at java.base/java.lang.Thread.run(Thread.java:1589)
```

## Expected Behavior
Ktlint should work as with version `0.50.0`.

**Comment by dmitry-weirdo** [comment]
This disable seems to work, thanks to https://pinterest.github.io/ktlint/1.0.1/rules/configuration-ktlint/#disabled-rules that provides the error.

```
# disable the failing rule after updating to 0.51.0-FINAL
# it depends on standard:indent which is disable above
# see https://pinterest.github.io/ktlint/1.0.1/rules/standard/#string-template-indent
# see https://pinterest.github.io/ktlint/1.0.1/rules/configuration-ktlint/#disabled-rules
# ktlint_standard_string_template_indent = disabled
ktlint_standard_string-template-indent = disabled
```

Although now thousands of the newly introduced rules are failing 🤦 , the current issue is fixed, so I am closing the ticket.

**Comment by dmitry-weirdo** [comment]
This disable seems to work, thanks to https://pinterest.github.io/ktlint/1.0.1/rules/configuration-ktlint/#disabled-rules that provides the error.

```
# disable the failing rule after updating to 0.51.0-FINAL
# it depends on standard:indent which is disable above
# see https://pinterest.github.io/ktlint/1.0.1/rules/standard/#string-template-indent
# see https://pinterest.github.io/ktlint/1.0.1/rules/configuration-ktlint/#disabled-rules
# ktlint_standard_string_template_indent = disabled
ktlint_standard_string-template-indent = disabled
```

Although now thousands of the newly introduced rules are failing 🤦 , the current issue is fixed, so I am closing the ticket.
