### ISSUE TITLE
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer exception thrown when .editorconfig file is present

### ISSUE THREAD

**Issue by pawelkw** [pinterest/ktlint#2370]
## Expected Behavior
KtLint should not throw an exception and print rule violations instead.

## Observed Behavior
```
> Task :application:spotlessKotlin FAILED
Step 'ktlint' found problem in 'src/main/kotlin/com/x/y/z/application/App.kt':
class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
        at com.pinterest.ktlint.ruleset.standard.rules.FunctionSignatureRule$Companion$FORCE_MULTILINE_WHEN_PARAMETER_COUNT_GREATER_OR_EQUAL_THAN_PROPERTY$1.invoke(FunctionSignatureRule.kt:749)
        at com.pinterest.ktlint.ruleset.standard.rules.FunctionSignatureRule$Companion$FORCE_MULTILINE_WHEN_PARAMETER_COUNT_GREATER_OR_EQUAL_THAN_PROPERTY$1.invoke(FunctionSignatureRule.kt:745)
        at com.pinterest.ktlint.rule.engine.core.api.editorconfig.EditorConfig.get(EditorConfig.kt:60)
        at com.pinterest.ktlint.ruleset.standard.rules.FunctionSignatureRule.beforeFirstNode(FunctionSignatureRule.kt:84)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext.executeRule(RuleExecutionContext.kt:54)
        at com.pinterest.ktlint.rule.engine.api.KtLintRuleEngine$format$3.invoke(KtLintRuleEngine.kt:146)
        at com.pinterest.ktlint.rule.engine.api.KtLintRuleEngine$format$3.invoke(KtLintRuleEngine.kt:145)
        at com.pinterest.ktlint.rule.engine.internal.VisitorProvider$visitor$3.invoke(VisitorProvider.kt:46)
        at com.pinterest.ktlint.rule.engine.internal.VisitorProvider$visitor$3.invoke(VisitorProvider.kt:44)
        at com.pinterest.ktlint.rule.engine.api.KtLintRuleEngine.format(KtLintRuleEngine.kt:145)
        at com.diffplug.spotless.glue.ktlint.compat.KtLintCompat1Dot0Dot0Adapter.format(KtLintCompat1Dot0Dot0Adapter.java:118)
```

## Steps to Reproduce
1. Apply spotless/ktlint as follows:
```
apply plugin: 'com.diffplug.spotless'

spotless {
    kotlin {
        target "**/*.kt"
        ktlint("1.0.1")
    }
}
```

2.  Add .editorconfig generated by ktlint CLI to root of Gradle project.
3. Run `check` or `spotlessCheck` or `spotlessApply` through gradlew.
4. Exception is thrown.

**If .editorconfig file is removed then expected behaviour is observed.**
Empty/commented out .editorconfig file still causes the exception!

## Your Environment

* Version of ktlint used: 1.0.1
* Relevant parts of the `.editorconfig` settings: 
Using the default .editorconfig generated using ktlint CLI using the official style
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): Spotless 6.22.0
* Version of Gradle used (if applicable): 7.3.3
* Operating System and version: MacOS 14.1.1

**Comment by pawelkw** [comment]
@paul-dingemans 
Does not seem to happen with the CLI indeed. I'm off to file a report at spotless instead. Sorry for the noise here. Thanks for help!
