### ISSUE TITLE
Can't printAST from stdin (Paths.get(fileName).parent must not be null)

### ISSUE THREAD

**Issue by jacquerie** [pinterest/ktlint#528]
The very example from the README (https://github.com/pinterest/ktlint#ast) does not appear to work with the latest `ktlint` installed through Homebrew:
```
$ ktlint --version
0.34.0

$ printf "fun main() {}" | ktlint --color printAST --stdin
Exception in thread "main" java.lang.IllegalStateException: Paths.get(fileName).parent must not be null
	at com.pinterest.ktlint.core.KtLint$userDataResolver$2.invoke(KtLint.kt:198)
	at com.pinterest.ktlint.core.KtLint$userDataResolver$2.invoke(KtLint.kt:41)
	at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:138)
	at com.pinterest.ktlint.internal.FileUtilsKt.lintFile(FileUtils.kt:51)
	at com.pinterest.ktlint.internal.FileUtilsKt.lintFile$default(FileUtils.kt:49)
	at com.pinterest.ktlint.internal.PrintASTSubCommand.printAST(PrintASTSubCommand.kt:69)
	at com.pinterest.ktlint.internal.PrintASTSubCommand.run(PrintASTSubCommand.kt:47)
	at com.pinterest.ktlint.Main.handleSubCommand(Main.kt:76)
	at com.pinterest.ktlint.Main.main(Main.kt:63)
```

**Comment by shashachu** [comment]
@jacquerie Thanks for the report; this is indeed a regression in 0.34.0. We have one other possible regression (#526), so I'll put up a fix for this one, and assuming that one also needs a fix, we can push out a 0.34.1 sometime this week. In the meantime, `printAST` that takes in a filename is still working, so you can use that as a workaround.
