### ISSUE TITLE
Executable JAR output by Gradle shadowJarExecutable task fails to output version

### ISSUE THREAD

**Issue by shashachu** [pinterest/ktlint#613]
```
./ktlint/build/run/ktlint --version
Exception in thread "main" picocli.CommandLine$ExecutionException: Could not get version info from com.pinterest.ktlint.internal.KtlintVersionProvider@7bb11784: java.lang.IllegalStateException: Failed to determine ktlint version
	at picocli.CommandLine$Model$CommandSpec.version(CommandLine.java:4131)
	at picocli.CommandLine.printVersionHelp(CommandLine.java:1672)
	at com.pinterest.ktlint.internal.CommandLineExtKt.printHelpOrVersionUsage(CommandLineExt.kt:17)
	at com.pinterest.ktlint.internal.CommandLineExtKt.printHelpOrVersionUsage$default(CommandLineExt.kt:11)
	at com.pinterest.ktlint.Main.main(Main.kt:56)
Caused by: java.lang.IllegalStateException: Failed to determine ktlint version
	at com.pinterest.ktlint.internal.KtlintVersionProvider.getVersion(KtlintVersionProvider.kt:21)
	at picocli.CommandLine$Model$CommandSpec.version(CommandLine.java:4128)
```

**Comment by shashachu** [comment]
Fixed by https://github.com/pinterest/ktlint/pull/614
