### ISSUE TITLE
Format fails with Unexpected indentation (2) (it should be 4)

### ISSUE THREAD

**Issue by ZacSweers** [pinterest/ktlint#632]
I'm trying to run a format call (via spotless apply), and it's throwing an exception on a formatting issue even though the goal it to have ti reformat it. Let me know if I'm missing something about how format is supposed to work for this case.

Repro: https://github.com/square/moshi/tree/z/spotless. Run `mvn spotless:apply`

```
Unexpected indentation (2) (it should be 4)
        at com.diffplug.spotless.kotlin.KtLintStep$State.lambda$createFormat$0(KtLintStep.java:134)
        at com.sun.proxy.$Proxy25.invoke(Unknown Source)
        at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:411)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.diffplug.spotless.kotlin.KtLintStep$State.lambda$createFormat$1(KtLintStep.java:173)
        at com.diffplug.spotless.FormatterFunc.apply(FormatterFunc.java:31)

```

**Comment by Tapchicoma** [comment]
Standard [indentation rule](https://github.com/pinterest/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/IndentationRule.kt) does not autocorrect this case.

Try to use new experimental [indentation rule](https://github.com/pinterest/ktlint/blob/master/ktlint-ruleset-experimental/src/main/kotlin/com/pinterest/ktlint/ruleset/experimental/IndentationRule.kt).

**Comment by ZacSweers** [comment]
Gotcha, will do.

**Comment by covercash2** [comment]
I'm getting this error as well, and the link to the solution is 404
