### ISSUE TITLE
Null Pointer Excetion when running from CLI

### ISSUE THREAD

**Issue by antonshilov** [pinterest/ktlint#690]
Crashes when running check on the project root, version `0.36.0`.
 ```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.pinterest.ktlint.KtlintCommandLine.parallel(Main.kt:531)
	at com.pinterest.ktlint.KtlintCommandLine.parallel$default(Main.kt:505)
	at com.pinterest.ktlint.KtlintCommandLine.lintFiles(Main.kt:264)
	at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:232)
	at com.pinterest.ktlint.Main.main(Main.kt:61)
Caused by: java.lang.NullPointerException
	at com.pinterest.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:152)
	at com.pinterest.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:45)
	at com.pinterest.ktlint.core.KtLint$visitor$2$1.invoke(KtLint.kt:285)
	at com.pinterest.ktlint.core.KtLint$visitor$2$1.invoke(KtLint.kt:45)
	at com.pinterest.ktlint.core.KtLint.visit(KtLint.kt:599)
	at com.pinterest.ktlint.core.KtLint.access$visit(KtLint.kt:45)
	at com.pinterest.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:283)
	at com.pinterest.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:45)
	at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:149)
	at com.pinterest.ktlint.internal.FileUtilsKt.lintFile(FileUtils.kt:51)
	at com.pinterest.ktlint.KtlintCommandLine.process(Main.kt:357)
	at com.pinterest.ktlint.KtlintCommandLine.access$process(Main.kt:115)
	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$2$1.call(Main.kt:256)
	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$2$1.call(Main.kt:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:819)
```

**Comment by Tapchicoma** [comment]
Could you try to narrow down on which file ktlint crashes and post this file here with file path?

**Comment by romtsn** [comment]
Closing due to inactivity. Feel free to reopen with more details.
