### ISSUE TITLE
Question for failed of step ktlintMainSourceSetCheck

### ISSUE THREAD

**Issue by seungdols** [pinterest/ktlint#698]
Hi, 

Thank you for make by good lint tool.

I will plan for using kotlin in production code, I have some issue. 

I need to lint tool for kotlin code. So, I decided this tool use.

It's use and then build failed. 

It's failed ktlintMainSourceSetCheck in build step.

* Kotlin version: 1.3.50
* Ktlint version: 9.2.1
* Java version: 1.8.222 (openjdk)

```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.ClassCastException: org.jetbrains.kotlin.com.intellij.psi.impl.file.PsiLargeTextFileImpl cannot be cast to org.jetbrains.kotlin.psi.KtFile
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.pinterest.ktlint.KtlintCommandLine.parallel(Main.kt:531)
	at com.pinterest.ktlint.KtlintCommandLine.parallel$default(Main.kt:505)
	at com.pinterest.ktlint.KtlintCommandLine.lintFiles(Main.kt:264)
	at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:232)
	at com.pinterest.ktlint.Main.main(Main.kt:61)
Caused by: java.lang.ClassCastException: org.jetbrains.kotlin.com.intellij.psi.impl.file.PsiLargeTextFileImpl cannot be cast to org.jetbrains.kotlin.psi.KtFile
	at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:137)
	at com.pinterest.ktlint.internal.FileUtilsKt.lintFile(FileUtils.kt:51)
	at com.pinterest.ktlint.KtlintCommandLine.process(Main.kt:357)
	at com.pinterest.ktlint.KtlintCommandLine.access$process(Main.kt:115)
	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$2$1.call(Main.kt:256)
	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$2$1.call(Main.kt:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

> Task :apps:api:ktlintMainSourceSetCheck FAILED
```
So, I try "build scan", It's a success.

This issue causes build failure of Jenkins(CI). Maybe Jenkins contains some issues.

Are you know this issue in Jenkins?

It’s reproducible in Jenkins. It’s the same reason.

You need to help me.

Thank you.

**Comment by Tapchicoma** [comment]
Original issue in ktlint-gradle: https://github.com/JLLeitschuh/ktlint-gradle/issues/340

@seungdols are you able to reproduce it locally on your machine? And if it is possible - could provide a file on which ktlint fails?

**Comment by seungdols** [comment]
@Tapchicoma No. I can't reproduce in locally Because It only cause in Jenkins.

**Comment by Tapchicoma** [comment]
Could you enable debug setting https://github.com/JLLeitschuh/ktlint-gradle#configuration:
```
    debug.set(true)
```
and paste CI output here?

**Comment by seungdols** [comment]
I will try it. Sorry So, I can't paste CI output because of company source code. 

I can only show part of output when It was error before. 

```
[DEBUG] Checking /jenkins_home/workspace/ build check/apps/api/build/resources/main/META-INF/application-cache.xml
[DEBUG] Checking /jenkins_home/workspace/ build check/apps/api/build/resources/main/META-INF/application-component.xml
[90m/jenkins_home/workspace/ build check/apps/api/build/kotlin/kaptGenerateStubsKotlin/caches-jvm/jvm/kotlin/[0msupertypes.tab_i[90m:[0m1[90m:1:[0m Not a valid Kotlin file (expecting an element) (cannot be auto-corrected)
[90m/jenkins_home/workspace/ build check/apps/api/build/kotlin/kaptGenerateStubsKotlin/caches-jvm/jvm/kotlin/[0msupertypes.tab_i.len[90m:[0m1[90m:1:[0m Not a valid Kotlin file (expecting an element) (cannot be auto-corrected)
[90m/jenkins_home/workspace/ build check/apps/api/build/kotlin/kaptGenerateStubsKotlin/[0mlast-build.bin[90m:[0m1[90m:1:[0m Not a valid Kotlin file (expecting an element) (cannot be auto-corrected)
[90m/jenkins_home/workspace/ build check/apps/api/build/ktlint/[0mktlintMainSourceSetCheck.args[90m:[0m4[90m:17:[0m Not a valid Kotlin file (unexpected tokens (use ';' to separate expressions on the same line)) (cannot be auto-corrected)
[DEBUG] Checking /jenkins_home/workspace/ build check/apps/api/build/resources/main/META-INF/application-datasources.xml
[DEBUG] Checking /jenkins_home/workspace/ build check/apps/api/build/resources/main/META-INF/application-kafka-configs.xml
[DEBUG] Checking /jenkins_home/workspace/ build check/apps/api/build/resources/main/META-INF/application-es-rest.xml
[DEBUG] Checking /jenkins_home/workspace/ build check/apps/api/build/resources/main/META-INF/application-kafka.xml
[DEBUG] Checking /jenkins_home/workspace/ build check/apps/api/build/libs/api-0.0.1-SNAPSHOT.war
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.ClassCastException: org.jetbrains.kotlin.com.intellij.psi.impl.file.PsiLargeTextFileImpl cannot be cast to org.jetbrains.kotlin.psi.KtFile
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.pinterest.ktlint.KtlintCommandLine.parallel(Main.kt:531)
	at com.pinterest.ktlint.KtlintCommandLine.parallel$default(Main.kt:505)
	at com.pinterest.ktlint.KtlintCommandLine.lintFiles(Main.kt:264)
	at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:232)
	at com.pinterest.ktlint.Main.main(Main.kt:61)
Caused by: java.lang.ClassCastException: org.jetbrains.kotlin.com.intellij.psi.impl.file.PsiLargeTextFileImpl cannot be cast to org.jetbrains.kotlin.psi.KtFile
	at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:137)
	at com.pinterest.ktlint.internal.FileUtilsKt.lintFile(FileUtils.kt:51)
	at com.pinterest.ktlint.KtlintCommandLine.process(Main.kt:357)
	at com.pinterest.ktlint.KtlintCommandLine.access$process(Main.kt:115)
	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$2$1.call(Main.kt:256)
	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$2$1.call(Main.kt:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

> Task :apps:api:ktlintMainSourceSetCheck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apps:api:ktlintMainSourceSetCheck'.
> Process 'command '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.el7_6.x86_64/bin/java'' finished with non-zero exit value 1
```

Sorry, It deleted directory name and path of CI server.

**Comment by Tapchicoma** [comment]
Strange that it tries to check `war` and `xml` files. Could you paste here your `ktlint-gradle` configuration?

ktlint itself should not fail when `war` file is passed to it:
```
Caused by: java.lang.ClassCastException: org.jetbrains.kotlin.com.intellij.psi.impl.file.PsiLargeTextFileImpl cannot be cast to org.jetbrains.kotlin.psi.KtFile
```

**Comment by seungdols** [comment]
Ah. Maybe … It was my mistake. I paste part of build.gradle for API server

```groovy
    
plugins {
    id 'war'
    id 'groovy'
    id 'org.jetbrains.kotlin.jvm' version '1.3.50'
    id 'org.jetbrains.kotlin.kapt' version "1.3.50"
    id 'org.jetbrains.kotlin.plugin.spring' version "1.3.50"
    id 'org.jlleitschuh.gradle.ktlint' version '9.2.1'
}

dependencies {
    compileOnly 'javax.servlet:javax.servlet-api:3.0.1'
    compileOnly 'javax.servlet.jsp:jsp-api:2.2'

    compile 'javax.servlet:jstl:1.2'
    compile 'ch.qos.logback:logback-classic:1.2.3'
    compile 'org.slf4j:slf4j-api:1.7.25'
    compile 'org.slf4j:jcl-over-slf4j:1.7.25'
    compile 'org.slf4j:log4j-over-slf4j:1.7.25'
    compile 'org.springframework.data:spring-data-redis:1.8.11.RELEASE'
    compile 'cglib:cglib-nodep:3.2.5'
    compile 'org.hibernate:hibernate-validator:5.1.1.Final'
    compile ('org.elasticsearch.client:elasticsearch-rest-high-level-client:6.8.0'){
        exclude group: 'commons-logging', module: 'commons-logging'
    }
    compile ('org.elasticsearch.client:elasticsearch-rest-client-sniffer:6.8.0'){
        exclude group: 'commons-logging', module: 'commons-logging'
    }
    compile 'com.google.code.gson:gson:2.8.2'
    compile ('org.eclipse.persistence:eclipselink:2.5.2'){
        exclude group: 'org.eclipse.persistence', module: 'commonj.sdo'
    }
    compile 'org.springframework.kafka:spring-kafka:1.3.5.RELEASE'
    compile ('org.apache.zookeeper:zookeeper:3.4.12'){
        exclude group: 'org.slf4j', module: 'slf4j-log4j12'
        exclude group: 'log4j', module: 'log4j'
    }
    compile 'org.springframework.data:spring-data-mongodb:1.10.11.RELEASE'
    compile 'io.springfox:springfox-swagger2:2.5.0'
    compile 'io.springfox:springfox-swagger-ui:2.5.0'
    compile 'com.fasterxml:classmate:1.4.0'

    compile group: 'com.fasterxml.jackson.module', name: 'jackson-module-kotlin', version: '2.9.7'
    compile group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib-jdk8', version: '1.3.50'
    compile group: 'org.jetbrains.kotlin', name: 'kotlin-reflect', version: '1.3.50'

...
}
```

**Comment by Tapchicoma** [comment]
@seungdols and no `ktlint { .. }` specific configuration block? So are used default settings? :thinking:

**Comment by seungdols** [comment]
@Tapchicoma There no `ktlint { }` block. I don't know if lint is trying to check, even though the part I wondered about is not a kotlin file.

**Comment by romtsn** [comment]
@seungdols feel free to reopen if the problem still exists

**Comment by nadim1044** [comment]
what is the solution?
