### ISSUE TITLE
 org.ec4j.core.parser.ParseException: Equals sign '==' missing after property name '' at 1:1 (0)

### ISSUE THREAD

**Issue by douglaskazumi** [pinterest/ktlint#790]
## Expected Behavior
Updating ktlint from 0.34.2 to 0.35.0+ shouldn't make ktlint task fail.

## Observed Behavior
ktlint fails with the following error:

```
Exception in thread "main" java.util.concurrent.ExecutionException: org.ec4j.core.parser.ParseException: Equals sign '==' missing after property name '' at 1:1 (0)
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.pinterest.ktlint.KtlintCommandLine.parallel(Main.kt:481)
        at com.pinterest.ktlint.KtlintCommandLine.parallel$default(Main.kt:455)
        at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:307)
        at com.pinterest.ktlint.Main.main(Main.kt:61)
Caused by: org.ec4j.core.parser.ParseException: Equals sign '==' missing after property name '' at 1:1 (0)
        at org.ec4j.core.parser.ErrorHandler$3.error(ErrorHandler.java:54)
        at org.ec4j.core.parser.EditorConfigParser.readProperty(EditorConfigParser.java:324)
        at org.ec4j.core.parser.EditorConfigParser.readLine(EditorConfigParser.java:180)
        at org.ec4j.core.parser.EditorConfigParser.readLines(EditorConfigParser.java:148)
        at org.ec4j.core.parser.EditorConfigParser.parse(EditorConfigParser.java:131)
        at com.pinterest.ktlint.core.internal.EditorConfigInternal$Companion.parseEditorconfigFile(EditorConfigInternal.kt:126)
        at com.pinterest.ktlint.core.internal.EditorConfigInternal$Companion.loadEditorconfigFile(EditorConfigInternal.kt:135)
        at com.pinterest.ktlint.core.internal.EditorConfigInternal$Companion.access$loadEditorconfigFile(EditorConfigInternal.kt:26)
        at com.pinterest.ktlint.core.internal.EditorConfigInternal$Companion$cached$1.of(EditorConfigInternal.kt:72)
        at com.pinterest.ktlint.core.KtLint$userDataResolver$2.invoke(KtLint.kt:200)
        at com.pinterest.ktlint.core.KtLint$userDataResolver$2.invoke(KtLint.kt:41)
        at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:361)
        at com.pinterest.ktlint.internal.FileUtilsKt.formatFile(FileUtils.kt:79)
        at com.pinterest.ktlint.KtlintCommandLine$run$1.invoke(Main.kt:240)
        at com.pinterest.ktlint.KtlintCommandLine$run$4$1.call(Main.kt:306)
        at com.pinterest.ktlint.KtlintCommandLine$run$4$1.call(Main.kt:115)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

## Steps to Reproduce
- Run `ktlint` on project with version 0.34.2. Task succeeds.
- Upgrade to 0.35.0 (or latest version)
- Run `ktlint`. Task fails.

## Your Environment

* Version of ktlint used: 0.35.0
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): Pretty much the same as readme except that the code is in a separate file called ktlint.gradle:

```
repositories {
    maven { url 'https://****************/nexus/content/repositories/public' }
}

configurations {
    ktlint
}

dependencies {
    ktlint "com.pinterest:ktlint:0.34.2"
}

task ktlint(type: JavaExec, group: "verification") {
    description = "Check Kotlin code style."
    classpath = configurations.ktlint
    main = "com.pinterest.ktlint.Main"
    args "src/**/*.kt"
}

task ktlintFormat(type: JavaExec, group: "formatting") {
    description = "Fix Kotlin code style deviations."
    classpath = configurations.ktlint
    main = "com.pinterest.ktlint.Main"
    args "-F", "src/**/*.kt"
}
```
* Version of Gradle used (if applicable): 3.6.3

**Comment by Tapchicoma** [comment]
Do you have `.editorconfig` in your project? Seems it does not correct according to specs.

**Comment by douglaskazumi** [comment]
Yes, I have it on the project root and it had the following:
```
[*.{kt,kts}]
disabled_rules=import-ordering
```

Once you posted your comment, I tried to change it to:
```
root = true

[*]
indent_style = space
indent_size = 2

end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.{kt,kts}]
indent_size = 4
disabled_rules=import-ordering
```

And it still didn't work

**Comment by Tapchicoma** [comment]
We have tests for parsing `.editorconfig` that also checks your simple case: https://github.com/pinterest/ktlint/blob/master/ktlint-core/src/test/kotlin/com/pinterest/ktlint/core/internal/EditorConfigLoaderTest.kt

Would be nice if you could either add a link to your repo and create small reproduction repository.

**Comment by douglaskazumi** [comment]
Ok, while I was trying to strip code from my project to share I've found the culprit. There was an empty `.editorconfig` file buried inside a subfolder of the project. After removing that file I was able to lint the project.

Would be very nice if somehow we could have the output for the file being parsed.

Thanks for the help

**Comment by Tapchicoma** [comment]
I've open a new issue in ec4j library (see linked one). Once it will be implemented, I will add more user friendly message in such cases.

**Comment by douglaskazumi** [comment]
Thanks for all the help!

**Comment by Tapchicoma** [comment]
@douglaskazumi next ktlint version should allow empty `.editorconfig` files and print the path to the failed one via https://github.com/pinterest/ktlint/pull/791.

Thank you for reporting this issue :+1:
